addAssignees: author

addReviewers: true

reviewers:
  - boatngin
  - Gameinwza
  - NTZ9008
  # - teammate3

# Number of reviewers to assign (0 = all)
numberOfReviewers: 1

# Skip auto-assign when PR title contains any of these keywords
skipKeywords:
  - wip
  - draft
