import type {
  AdminCardAttributesData,
  AdminCommissionData,
  AdminOverviewData,
  AdminOrdersData,
  AdminUsersData,
} from "@/features/admin/admin.types";

const SPARK_BARS = [9, 14, 11, 18, 13, 22, 17, 26];

export const ADMIN_OVERVIEW_FIXTURE: AdminOverviewData = {
  title: "ภาพรวมแพลตฟอร์ม",
  subtitle:
    "สรุปผลประกอบการและกิจกรรมทั้งหมดบน Pegasus TCG · อัปเดตล่าสุด 5 นาทีที่แล้ว",

  stats: [
    {
      id: "gmv",
      label: "ยอดขายรวมเดือนนี้",
      value: "฿428,500",
      delta: "+18.2%",
      footnote: "เทียบกับ ฿362,400 เดือนก่อน",
      bars: SPARK_BARS,
      accent: "primary",
    },
    {
      id: "new-sellers",
      label: "ผู้ขายรายใหม่",
      value: "32",
      delta: "+9.4%",
      footnote: "ผ่านการยืนยัน KYC แล้ว",
      bars: SPARK_BARS,
      accent: "teal",
    },
    {
      id: "active-listings",
      label: "ประกาศขายที่ใช้งานอยู่",
      value: "6,184",
      delta: "+3.1%",
      footnote: "จาก 442 ร้านค้าทั่วแพลตฟอร์ม",
      bars: SPARK_BARS,
      accent: "primary",
    },
    {
      id: "commission",
      label: "ค่าคอมมิชชั่นที่เก็บได้",
      value: "฿12,850",
      delta: "+18.2%",
      footnote: "เฉลี่ย 3.0% ของยอดขายรวม",
      bars: SPARK_BARS,
      accent: "green",
    },
  ],

  monthlySales: {
    title: "ยอดขายรายเดือน",
    description: "แสดงยอดขายรวม 6 เดือนล่าสุด (บาท)",
    points: [
      { month: "ม.ค.", singles: 182000, sealed: 96000 },
      { month: "ก.พ.", singles: 168000, sealed: 104000 },
      { month: "มี.ค.", singles: 214000, sealed: 118000 },
      { month: "เม.ย.", singles: 236000, sealed: 132000 },
      { month: "พ.ค.", singles: 258000, sealed: 148000 },
      { month: "มิ.ย.", singles: 284000, sealed: 164000 },
    ],
  },

  activity: {
    title: "กิจกรรมล่าสุด",
    description: "เหตุการณ์สำคัญที่ต้องรับทราบ",
    actionLabel: "ดูกิจกรรมทั้งหมด",
    items: [
      {
        id: "act-1",
        initials: "MT",
        avatarAccent: "teal",
        name: "minmin_tcg",
        time: "· 5 นาที",
        message: "ส่งเอกสาร KYC เพื่อขอเปิดร้าน",
        status: "pending",
        statusLabel: "รอตรวจสอบ",
      },
      {
        id: "act-2",
        initials: "SY",
        avatarAccent: "red",
        name: "ระบบ",
        time: "· 22 นาที",
        message: "ตรวจพบประกาศขายราคาผิดปกติ 3 รายการ",
        status: "attention",
        statusLabel: "ต้องตรวจสอบ",
      },
      {
        id: "act-3",
        initials: "KP",
        avatarAccent: "primary",
        name: "kandypop",
        time: "· 1 ชม.",
        message: "ขอเพิ่มการ์ดใหม่เข้าแคตตาล็อก",
        status: "pending",
        statusLabel: "รออนุมัติ",
      },
      {
        id: "act-4",
        initials: "ST",
        avatarAccent: "primary",
        name: "sora.trades",
        time: "· 2 ชม.",
        message: "ร้องเรียนคำสั่งซื้อ ORD-10201",
        status: "attention",
        statusLabel: "เปิดเคสแล้ว",
      },
      {
        id: "act-5",
        initials: "PH",
        avatarAccent: "green",
        name: "pika.hunter",
        time: "· 4 ชม.",
        message: "ยืนยันตัวตนผ่านเรียบร้อย",
        status: "success",
        statusLabel: "สำเร็จ",
      },
    ],
  },

  topSellers: {
    title: "ร้านค้าที่ทำยอดขายสูงสุด",
    description: "จัดอันดับตามยอดขายเดือนสิงหาคม 2569",
    items: [
      { id: "s1", name: "minmin_tcg", amount: "฿86,400", percent: 100 },
      { id: "s2", name: "kandypop", amount: "฿62,180", percent: 72 },
      { id: "s3", name: "sora.trades", amount: "฿48,900", percent: 57 },
      { id: "s4", name: "pika.hunter", amount: "฿31,250", percent: 36 },
      { id: "s5", name: "tcg.bkk", amount: "฿24,700", percent: 29 },
    ],
  },

  gameShare: {
    title: "สัดส่วนยอดขายตามเกม",
    description: "ม.ค. - มิ.ย. 2569",
    slices: [
      { id: "pokemon", name: "Pokémon", value: 46 },
      { id: "one-piece", name: "One Piece", value: 22 },
      { id: "union-arena", name: "Union Arena", value: 14 },
      { id: "yugioh", name: "Yu-Gi-Oh!", value: 11 },
      { id: "others", name: "อื่น ๆ", value: 7 },
    ],
    footnoteTitle: "Pokémon ครองส่วนแบ่ง 46%",
    footnoteDescription: "ข้อมูลจากคำสั่งซื้อที่สำเร็จแล้ว",
  },
};

export const ADMIN_CARD_ATTRIBUTES_FIXTURE: AdminCardAttributesData = {
  title: "คุณสมบัติการ์ด",
  subtitle:
    "กำหนดว่าการ์ดแต่ละเกมมีข้อมูลอะไรบ้าง — ใช้สร้างตัวกรองและฟอร์มลงขายอัตโนมัติ",

  actions: {
    viewJsonLabel: "ดูเป็น JSON",
    saveLabel: "บันทึก schema",
  },

  notice:
    'การแก้ไข schema จะมีผลกับฟอร์มลงขายของผู้ขายทันที — ฟิลด์ที่ตั้งเป็น "จำเป็น" จะบังคับกรอกในประกาศขายใหม่ทั้งหมด',

  gamePicker: { title: "เลือกเกม" },

  fieldTypes: {
    title: "ประเภทฟิลด์ที่รองรับ",
    items: [
      { type: "text", description: "ข้อความสั้น" },
      { type: "number", description: "ตัวเลข" },
      { type: "enum", description: "ตัวเลือก" },
      { type: "boolean", description: "ใช่/ไม่ใช่" },
    ],
  },

  table: {
    addFieldLabel: "+ เพิ่มฟิลด์",
    columns: {
      name: "ชื่อฟิลด์",
      type: "ประเภท",
      sample: "ค่าตัวอย่าง",
      required: "จำเป็น",
      filterable: "ใช้กรอง",
      actions: "ตัวเลือกเพิ่มเติม",
    },
  },

  defaultGameId: "pokemon",

  games: [
    {
      id: "pokemon",
      name: "Pokémon",
      cardCount: "8,420",
      fields: [
        {
          id: "pokemon-hp",
          label: "HP",
          type: "number",
          sample: "60 / 120 / 340",
          required: true,
          filterable: true,
        },
        {
          id: "pokemon-card-type",
          label: "Card Type",
          type: "enum",
          sample: "Fire, Water, Grass, ...",
          required: true,
          filterable: true,
        },
        {
          id: "pokemon-rarity",
          label: "Rarity",
          type: "enum",
          sample: "Common, Rare, Secret Rare",
          required: true,
          filterable: true,
        },
        {
          id: "pokemon-set-number",
          label: "Set Number",
          type: "text",
          sample: "054/197",
          required: true,
          filterable: false,
        },
        {
          id: "pokemon-illustrator",
          label: "Illustrator",
          type: "text",
          sample: "Mitsuhiro Arita",
          required: false,
          filterable: false,
        },
        {
          id: "pokemon-retreat-cost",
          label: "Retreat Cost",
          type: "number",
          sample: "0 – 4",
          required: false,
          filterable: true,
        },
        {
          id: "pokemon-is-holographic",
          label: "Is Holographic",
          type: "boolean",
          sample: "ใช่ / ไม่ใช่",
          required: false,
          filterable: true,
        },
        {
          id: "pokemon-regulation-mark",
          label: "Regulation Mark",
          type: "text",
          sample: "G / H",
          required: false,
          filterable: false,
        },
      ],
    },
    {
      id: "one-piece",
      name: "One Piece",
      cardCount: "4,190",
      fields: [
        {
          id: "one-piece-card-type",
          label: "Card Type",
          type: "enum",
          sample: "Leader, Character, Event, Stage",
          required: true,
          filterable: true,
        },
        {
          id: "one-piece-color",
          label: "Color",
          type: "enum",
          sample: "Red, Green, Blue, Purple, ...",
          required: true,
          filterable: true,
        },
        {
          id: "one-piece-cost",
          label: "Cost",
          type: "number",
          sample: "0 – 10",
          required: true,
          filterable: true,
        },
        {
          id: "one-piece-power",
          label: "Power",
          type: "number",
          sample: "1000 / 5000 / 10000",
          required: false,
          filterable: true,
        },
        {
          id: "one-piece-counter",
          label: "Counter",
          type: "number",
          sample: "1000 / 2000",
          required: false,
          filterable: false,
        },
        {
          id: "one-piece-set-number",
          label: "Set Number",
          type: "text",
          sample: "OP01-001",
          required: true,
          filterable: false,
        },
      ],
    },
    {
      id: "mtg",
      name: "Magic: The Gathering",
      cardCount: "3,510",
      fields: [
        {
          id: "mtg-mana-cost",
          label: "Mana Cost",
          type: "text",
          sample: "{2}{U}{U}",
          required: true,
          filterable: true,
        },
        {
          id: "mtg-card-type",
          label: "Card Type",
          type: "enum",
          sample: "Creature, Instant, Land, ...",
          required: true,
          filterable: true,
        },
        {
          id: "mtg-rarity",
          label: "Rarity",
          type: "enum",
          sample: "Common, Uncommon, Rare, Mythic",
          required: true,
          filterable: true,
        },
        {
          id: "mtg-power-toughness",
          label: "Power / Toughness",
          type: "text",
          sample: "3 / 4",
          required: false,
          filterable: true,
        },
        {
          id: "mtg-set-code",
          label: "Set Code",
          type: "text",
          sample: "MOM · 121",
          required: true,
          filterable: false,
        },
        {
          id: "mtg-artist",
          label: "Artist",
          type: "text",
          sample: "Rebecca Guay",
          required: false,
          filterable: false,
        },
        {
          id: "mtg-is-foil",
          label: "Is Foil",
          type: "boolean",
          sample: "ใช่ / ไม่ใช่",
          required: false,
          filterable: true,
        },
      ],
    },
    {
      id: "yugioh",
      name: "Yu-Gi-Oh!",
      cardCount: "2,180",
      fields: [
        {
          id: "yugioh-card-type",
          label: "Card Type",
          type: "enum",
          sample: "Monster, Spell, Trap",
          required: true,
          filterable: true,
        },
        {
          id: "yugioh-attribute",
          label: "Attribute",
          type: "enum",
          sample: "DARK, LIGHT, WATER, ...",
          required: false,
          filterable: true,
        },
        {
          id: "yugioh-level",
          label: "Level / Rank",
          type: "number",
          sample: "1 – 12",
          required: false,
          filterable: true,
        },
        {
          id: "yugioh-atk-def",
          label: "ATK / DEF",
          type: "text",
          sample: "2500 / 2100",
          required: false,
          filterable: false,
        },
        {
          id: "yugioh-set-number",
          label: "Set Number",
          type: "text",
          sample: "LOB-EN001",
          required: true,
          filterable: false,
        },
      ],
    },
    {
      id: "sports",
      name: "Sports Cards",
      cardCount: "640",
      fields: [
        {
          id: "sports-sport",
          label: "Sport",
          type: "enum",
          sample: "Basketball, Football, Baseball",
          required: true,
          filterable: true,
        },
        {
          id: "sports-player",
          label: "Player",
          type: "text",
          sample: "LeBron James",
          required: true,
          filterable: true,
        },
        {
          id: "sports-season",
          label: "Season",
          type: "text",
          sample: "2023-24",
          required: true,
          filterable: true,
        },
        {
          id: "sports-is-graded",
          label: "Is Graded",
          type: "boolean",
          sample: "ใช่ / ไม่ใช่",
          required: false,
          filterable: true,
        },
      ],
    },
  ],
};

export const ADMIN_COMMISSION_FIXTURE: AdminCommissionData = {
  title: "ค่าคอมมิชชั่น",
  subtitle:
    "กำหนดอัตราค่าธรรมเนียมที่แพลตฟอร์มเก็บจากผู้ขายในแต่ละหมวดหมู่",
  actions: {
    historyLabel: "ดูประวัติการแก้ไข",
    saveLabel: "บันทึกการตั้งค่า",
  },
  defaultRate: {
    title: "อัตราเริ่มต้นทั้งแพลตฟอร์ม",
    description: "ใช้กับทุกหมวดหมู่ที่ไม่ได้ตั้งค่าเฉพาะไว้",
    value: "5.0",
    minLabel: "0%",
    maxLabel: "15%",
    recommendedLabel: "แนะนำ 3–7%",
    max: 15,
  },
  categories: {
    title: "อัตราเฉพาะหมวดหมู่",
    description: "เปิดสวิตช์เพื่อกำหนดอัตราแยกจากค่าเริ่มต้น",
    addLabel: "+ เพิ่มหมวดหมู่",
    items: [
      {
        id: "pokemon",
        name: "Pokémon",
        description: "การ์ดเดี่ยวและกล่องสุ่ม",
        rate: "5.0",
        useCustom: false,
        customLabel: "ตั้งค่าเฉพาะ",
        defaultLabel: "ใช้ค่าเริ่มต้น",
      },
      {
        id: "one-piece",
        name: "One Piece",
        description: "การ์ดเดี่ยวและกล่องสุ่ม",
        rate: "5.0",
        useCustom: false,
        customLabel: "ตั้งค่าเฉพาะ",
        defaultLabel: "ใช้ค่าเริ่มต้น",
      },
      {
        id: "sports-cards",
        name: "Sports Cards",
        description: "ต้องตรวจสอบความแท้เพิ่มเติม",
        rate: "7.0",
        useCustom: true,
        customLabel: "ตั้งค่าเฉพาะ",
        defaultLabel: "ใช้ค่าเริ่มต้น",
      },
      {
        id: "mtg",
        name: "Magic: The Gathering",
        description: "การ์ดเดี่ยว",
        rate: "5.0",
        useCustom: false,
        customLabel: "ตั้งค่าเฉพาะ",
        defaultLabel: "ใช้ค่าเริ่มต้น",
      },
      {
        id: "sealed",
        name: "กล่อง/ซองสุ่ม (ทุกเกม)",
        description: "สินค้าซีลปิดผนึก",
        rate: "3.5",
        useCustom: true,
        customLabel: "ตั้งค่าเฉพาะ",
        defaultLabel: "ใช้ค่าเริ่มต้น",
      },
    ],
  },
  calculation: {
    title: "ตัวอย่างการคำนวณ",
    rows: [
      { id: "price", label: "ราคาขาย", value: "฿1,290" },
      { id: "commission", label: "ค่าคอมมิชชั่น (5.0%)", value: "− ฿64.50" },
      { id: "fixed", label: "ค่าธรรมเนียมคงที่", value: "− ฿0.00" },
    ],
    totalLabel: "ผู้ขายได้รับ",
    totalValue: "฿1,225.50",
  },
  rules: {
    title: "กฎการเก็บค่าธรรมเนียม",
    items: [
      { id: "on-success", label: "เก็บเมื่อคำสั่งซื้อสำเร็จ", active: true },
      { id: "exclude-shipping", label: "ยกเว้นค่าส่ง", active: true },
      { id: "refund-on-cancel", label: "คืนค่าธรรมเนียมเมื่อยกเลิก", active: true },
      { id: "buyer-pays", label: "เก็บกับผู้ซื้อแทนผู้ขาย", active: false },
    ],
  },
  impact: {
    title: "ผลกระทบต่อผู้ขาย",
    description:
      "การขึ้นอัตราจะมีผลกับคำสั่งซื้อใหม่เท่านั้น และระบบจะแจ้งผู้ขายล่วงหน้า 14 วันโดยอัตโนมัติ",
  },
};

export const ADMIN_USERS_FIXTURE: AdminUsersData = {
  title: "จัดการผู้ใช้",
  subtitle: "ผู้ใช้ทั้งหมด 4,982 บัญชี · ผู้ซื้อ 4,540 · ผู้ขาย 442 · ระงับ 8",
  actions: { exportLabel: "ส่งออก CSV", addAdminLabel: "+ เพิ่มผู้ดูแล" },
  toolbar: {
    searchPlaceholder: "ค้นหาชื่อผู้ใช้, อีเมล, เบอร์โทร...",
    selects: [
      {
        id: "role",
        placeholder: "บทบาท: ทั้งหมด",
        options: [
          { value: "all", label: "บทบาท: ทั้งหมด" },
          { value: "buyer", label: "ผู้ซื้อ" },
          { value: "seller", label: "ผู้ขาย" },
          { value: "admin", label: "ผู้ดูแล" },
        ],
      },
      {
        id: "status",
        placeholder: "สถานะ: ทั้งหมด",
        options: [
          { value: "all", label: "สถานะ: ทั้งหมด" },
          { value: "active", label: "ใช้งานปกติ" },
          { value: "kyc-pending", label: "รอยืนยัน KYC" },
          { value: "suspended", label: "ถูกระงับ" },
        ],
      },
    ],
    advancedLabel: "ตัวกรองขั้นสูง",
    appliedLabel: "ตัวกรองที่ใช้:",
    chips: [
      { id: "joined-30d", label: "สมัครใน 30 วัน" },
      { id: "orders-gt-3", label: "มีคำสั่งซื้อ > 3" },
    ],
    clearLabel: "ล้างทั้งหมด",
  },
  table: {
    columns: {
      user: "ผู้ใช้",
      role: "บทบาท",
      orders: "คำสั่งซื้อ",
      spend: "ยอดใช้จ่าย",
      joinedAt: "สมัครเมื่อ",
      status: "สถานะ",
      actions: "ตัวเลือกเพิ่มเติม",
    },
    selectAllLabel: "เลือกผู้ใช้ทั้งหมดในหน้านี้",
    selectRowLabel: "เลือกผู้ใช้",
  },
  users: [
    {
      id: "nattapong-p",
      handle: "nattapong_p",
      email: "nattapong@example.com",
      initials: "NP",
      avatarAccent: "primary",
      role: "buyer",
      roleLabel: "ผู้ซื้อ",
      orders: "24",
      spend: "฿18,420",
      joinedAt: "12 ม.ค. 2568",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
    {
      id: "minmin-tcg",
      handle: "minmin_tcg",
      email: "minmin@example.com",
      initials: "MT",
      avatarAccent: "teal",
      role: "seller",
      roleLabel: "ผู้ขาย",
      orders: "186",
      spend: "฿86,400",
      joinedAt: "03 ม.ค. 2567",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
    {
      id: "kandypop",
      handle: "kandypop",
      email: "kandy@example.com",
      initials: "KP",
      avatarAccent: "teal",
      role: "seller",
      roleLabel: "ผู้ขาย",
      orders: "142",
      spend: "฿62,180",
      joinedAt: "22 มี.ค. 2567",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
    {
      id: "sora-trades",
      handle: "sora.trades",
      email: "sora@example.com",
      initials: "ST",
      avatarAccent: "teal",
      role: "seller",
      roleLabel: "ผู้ขาย",
      orders: "98",
      spend: "฿48,900",
      joinedAt: "15 พ.ค. 2567",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
    {
      id: "pika-hunter",
      handle: "pika.hunter",
      email: "pika@example.com",
      initials: "PH",
      avatarAccent: "primary",
      role: "buyer",
      roleLabel: "ผู้ซื้อ",
      orders: "41",
      spend: "฿31,250",
      joinedAt: "08 ก.ค. 2568",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
    {
      id: "fakeacc-099",
      handle: "fakeacc_099",
      email: "fake099@example.com",
      initials: "FA",
      avatarAccent: "slate",
      role: "buyer",
      roleLabel: "ผู้ซื้อ",
      orders: "2",
      spend: "฿640",
      joinedAt: "01 ส.ค. 2569",
      status: "suspended",
      statusLabel: "ถูกระงับ",
    },
    {
      id: "tcg-bangkok",
      handle: "tcg.bangkok",
      email: "tcgbkk@example.com",
      initials: "TB",
      avatarAccent: "amber",
      role: "seller",
      roleLabel: "ผู้ขาย",
      orders: "0",
      spend: "฿0",
      joinedAt: "13 ส.ค. 2569",
      status: "kycPending",
      statusLabel: "รอยืนยัน KYC",
    },
    {
      id: "rare-gems",
      handle: "rare.gems",
      email: "raregems@example.com",
      initials: "RG",
      avatarAccent: "primary",
      role: "buyer",
      roleLabel: "ผู้ซื้อ",
      orders: "7",
      spend: "฿4,180",
      joinedAt: "29 ก.ค. 2569",
      status: "active",
      statusLabel: "ใช้งานปกติ",
    },
  ],
  pagination: {
    summary: "แสดง 1–8 จาก 4,982 บัญชี",
    previousLabel: "ก่อนหน้า",
    nextLabel: "ถัดไป",
    pages: ["1", "2", "3"],
    activePage: "1",
    hasMore: true,
  },
};

export const ADMIN_ORDERS_FIXTURE: AdminOrdersData = {
  title: "ภาพรวมคำสั่งซื้อ",
  subtitle:
    "ติดตามคำสั่งซื้อทั้งแพลตฟอร์มตามสถานะ · แพลตฟอร์มไม่ถือเงิน ผู้ซื้อโอนตรงให้ผู้ขาย",
  actions: { exportLabel: "ส่งออก CSV", disputeLabel: "จัดการข้อพิพาท" },
  notice: {
    title: "มี 11 คำสั่งซื้อที่เปิดข้อพิพาท และ 6 รายการค้างชำระเกิน 48 ชม.",
    description:
      "คำสั่งซื้อที่ค้างชำระเกินกำหนดจะถูกยกเลิกอัตโนมัติและคืนสต็อกให้ผู้ขาย",
  },
  moreLabel: "ดูเพิ่มเติม",
  columns: [
    {
      id: "pending",
      tone: "pending",
      title: "รอชำระเงิน",
      count: "23",
      showMore: true,
      cards: [
        {
          id: "ord-10233",
          code: "ORD-10233",
          amount: "฿640",
          seller: "kandypop",
          buyer: "sora.trades",
          contextLabel: "ค้าง 4 ชม.",
          itemsLabel: "2 ใบ",
        },
        {
          id: "ord-10230",
          code: "ORD-10230",
          amount: "฿1,180",
          seller: "minmin_tcg",
          buyer: "pika.hunter",
          contextLabel: "ค้าง 12 ชม.",
          itemsLabel: "1 ใบ",
        },
        {
          id: "ord-10228",
          code: "ORD-10228",
          amount: "฿2,340",
          seller: "tcg.bangkok",
          buyer: "nattapong_p",
          contextLabel: "ค้าง 46 ชม.",
          itemsLabel: "3 ใบ",
        },
      ],
    },
    {
      id: "packing",
      tone: "packing",
      title: "ชำระแล้ว · รอส่ง",
      count: "34",
      showMore: true,
      cards: [
        {
          id: "ord-10241",
          code: "ORD-10241",
          amount: "฿1,850",
          seller: "minmin_tcg",
          buyer: "nattapong_p",
          contextLabel: "รอแพ็ค 2 ชม.",
          itemsLabel: "4 ใบ",
        },
        {
          id: "ord-10239",
          code: "ORD-10239",
          amount: "฿920",
          seller: "kandypop",
          buyer: "rare.gems",
          contextLabel: "รอแพ็ค 5 ชม.",
          itemsLabel: "1 ใบ",
        },
        {
          id: "ord-10236",
          code: "ORD-10236",
          amount: "฿3,410",
          seller: "sora.trades",
          buyer: "cardsdeal.th",
          contextLabel: "รอแพ็ค 8 ชม.",
          itemsLabel: "6 ใบ",
        },
      ],
    },
    {
      id: "shipping",
      tone: "shipping",
      title: "กำลังจัดส่ง",
      count: "312",
      showMore: true,
      cards: [
        {
          id: "ord-10238",
          code: "ORD-10238",
          amount: "฿3,420",
          seller: "sora.trades",
          buyer: "minmin_tcg",
          contextLabel: "TH2408xxxx91",
          itemsLabel: "5 ใบ",
        },
        {
          id: "ord-10235",
          code: "ORD-10235",
          amount: "฿780",
          seller: "pika.hunter",
          buyer: "kandypop",
          contextLabel: "TH2408xxxx84",
          itemsLabel: "1 ใบ",
        },
        {
          id: "ord-10231",
          code: "ORD-10231",
          amount: "฿1,560",
          seller: "cardsdeal.th",
          buyer: "tcg.bangkok",
          contextLabel: "TH2408xxxx77",
          itemsLabel: "3 ใบ",
        },
      ],
    },
    {
      id: "success",
      tone: "success",
      title: "สำเร็จ",
      count: "1,398",
      showMore: true,
      cards: [
        {
          id: "ord-10229",
          code: "ORD-10229",
          amount: "฿990",
          seller: "pika.hunter",
          buyer: "sora.trades",
          contextLabel: "รีวิว 5 ดาว",
          itemsLabel: "2 ใบ",
        },
        {
          id: "ord-10225",
          code: "ORD-10225",
          amount: "฿2,180",
          seller: "minmin_tcg",
          buyer: "kandypop",
          contextLabel: "รีวิว 5 ดาว",
          itemsLabel: "7 ใบ",
        },
        {
          id: "ord-10221",
          code: "ORD-10221",
          amount: "฿450",
          seller: "kandypop",
          buyer: "nattapong_p",
          contextLabel: "ยังไม่รีวิว",
          itemsLabel: "1 ใบ",
        },
      ],
    },
    {
      id: "dispute",
      tone: "dispute",
      title: "ข้อพิพาท",
      count: "11",
      // คอลัมน์นี้ในดีไซน์มีแค่ 2 ใบ ไม่มีปุ่ม "ดูเพิ่มเติม"
      showMore: false,
      cards: [
        {
          id: "ord-10201",
          code: "ORD-10201",
          amount: "฿4,200",
          seller: "pika.hunter",
          buyer: "sora.trades",
          contextLabel: "สินค้าไม่ตรงปก",
          itemsLabel: "3 ใบ",
        },
        {
          id: "ord-10188",
          code: "ORD-10188",
          amount: "฿1,340",
          seller: "rare.gems",
          buyer: "minmin_tcg",
          contextLabel: "ไม่ได้รับสินค้า",
          itemsLabel: "1 ใบ",
        },
      ],
    },
  ],
};
